# Generated by Django 3.2.6 on 2022-02-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_specifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryspecification',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
