# Generated by Django 3.2.6 on 2021-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnmover',
            name='engine_capacity',
            field=models.CharField(max_length=30, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='lawnmover',
            name='rotational_moment',
            field=models.CharField(max_length=30, verbose_name='Обороты'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='brightness',
            field=models.CharField(max_length=30, verbose_name='Частота обновления'),
        ),
    ]
