# Generated by Django 3.2.6 on 2021-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_final_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditioner',
            options={'verbose_name_plural': 'Conditioners'},
        ),
        migrations.AlterModelOptions(
            name='lawnmover',
            options={'verbose_name_plural': 'Lawnmovers'},
        ),
        migrations.AlterModelOptions(
            name='photocamera',
            options={'verbose_name_plural': 'Photocameras'},
        ),
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name_plural': 'Smartphones'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name_plural': 'TVs'},
        ),
        migrations.AlterModelOptions(
            name='videogameconsole',
            options={'verbose_name_plural': 'Videogame consoles'},
        ),
        migrations.AlterModelOptions(
            name='washingmachine',
            options={'verbose_name_plural': 'Washing machines'},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Финальная цена'),
        ),
    ]
