# Generated by Django 3.2.6 on 2021-10-10 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211010_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания заказа'),
        ),
    ]
