# Generated by Django 3.2.6 on 2021-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Конечная цена'),
        ),
    ]
